server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message

  ##activemq连接信息
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: zhouben166@163.com
    password: zhouben166
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
